### ISSUE TITLE
Ability to Force Double page mode or single page mode in certain books

### ISSUE THREAD

**Issue by deip** [deip/flipbook#19]
Some flip-book are better viewed in double page mode or single page mode, so this can be handy.

**Comment by deip** [comment]
It was already available in core, needed for wordpress

**Comment by wakasavan** [comment]
how this will work for ipad or mobile devices

**Comment by deip** [comment]
Hi Muhammad,
Currently PageMode has three stages:

`DFLIP.PAGE_MODE.AUTO, DFLIP.PAGE_MODE.SINGLE, DFLIP.PAGE_MODE.DOUBLE`

By default it it set to auto, so in web it acts as double page and in ipad or mobile it acts as single page.

But in-case some flip-books require double or single page mode explicitly. then it can be set as needed.

Though it's available in jQuery Plugin, Wordpress Plugin lacks the setting and will be added soon

**Comment by deip** [comment]
Feature added needs release.
